### ISSUE TITLE
Overlay on a video in real time

### ISSUE THREAD

**Issue by MPForte** [danielsnider/image_overlay_compass_and_scale#1]
I'd like to overlay an image (let's suppose "compass.png" ) over a video acquired in real time. The topic of the images of my video is /image_raw.

So basically in `./src/image_overlay/image_overlay.py --input-image ~/mars.png --heading 67 --scale-text 12 --output-file output.png` having the topic` /image_raw` instead of `~/mars.png`

Any idea? Thanks

**Comment by danielsnider** [comment]
To do live don't use the CLI interface, use ros by doing the following:

```
roslaunch image_overlay_compass_and_scale overlay.launch
```

To use your topic `/image_raw`, change in this file:
https://github.com/danielsnider/image_overlay_scale_and_compass/blob/master/launch/overlay.launch

Change `to="usb_cam/image_raw/compressed"` to `to="/image_raw"`

**Comment by MPForte** [comment]
Thanks.
I previously tried with it. However, when I try to see the overlay image I always obtained this error
```
Can't convert image: Unsupported image format: 8UC3
Disabling renderer on overlay
```
(using `rqt_bag` if I save the topic with `rosbag record`)

or 

```
[ INFO] [1518453800.426853051]: Using transport "raw"
[ERROR] [1518453800.732399098]: Unable to convert '8UC3' image for display: 'cv_bridge.cvtColorForDisplay() while trying to convert image from '8UC3' to 'bgr8' an exception was thrown ([8UC3] is not a color format. but [bgr8] is. The conversion does not make sense)'
```

by using `rosrun image_view image_view image:=overlay`

Ps. I'm working with the entire image and not with the compressed one, so I changed all the relative parameters in `image_overlay.py`, such as `from sensor_msgs.msg import Image` instead of `from sensor_msgs.msg import CompressedImage`

**Comment by danielsnider** [comment]
Good work trying to switch `image_overlay.py` to non-compressed image format. Either keep trying, or maybe more quickly republish your raw stream as compressed using this easy command:
```
rosrun image_transport republish raw   in:=/image_raw   out:=/image_compressed
```
I think this gives you both compressed and theora streams, check the produced output topics and choose the compressed topic to use with `image_overlay`.

**Comment by MPForte** [comment]
solved! To resolve the cv_bridge issue, I added `encoding="bgr8"`  here:
`image = CvBridge().cv2_to_imgmsg(img)`
`image = CvBridge().cv2_to_imgmsg(img, encoding="bgr8")`

Thank you for your quick and kind help.

**Comment by danielsnider** [comment]
Great work! I would love to see your working branch. I would like to integrate support for raw! You could even make a pull request here.

Have a great day!
